'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'

export default function TermsOfService() {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })

  return (
    <div className="z-content always-visible">
      {/* Header */}
      <div className="relative py-24 lg:py-32">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center"
          >
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-6 drop-shadow-lg">
              Terms of Service
            </h1>
            <p className="text-xl text-white/80 mb-8 drop-shadow-md">
              These terms govern your use of One Call Away's virtual assistant and cold-calling services.
            </p>
            <p className="text-white/70 drop-shadow-sm">
              Last updated: {currentDate}
            </p>
          </motion.div>
        </div>
      </div>

      {/* Content */}
      <div className="relative py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="professional-glass-strong rounded-3xl p-8 lg:p-12"
          >
            <div className="prose prose-lg max-w-none">
              
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">1. Acceptance of Terms</h2>
                <p className="text-secondary-700">
                  By accessing and using One Call Away's services ("Services"), you agree to be bound by these Terms of Service ("Terms"). These Terms constitute a legally binding agreement between you ("Client," "you," or "your") and One Call Away ("Company," "we," "us," or "our"). If you do not agree to these Terms, you may not use our Services.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">2. Service Description</h2>
                <p className="text-secondary-700 mb-4">
                  One Call Away provides professional virtual assistant and cold-calling services specifically designed for real estate professionals, including but not limited to:
                </p>
                <ul className="list-disc list-inside text-secondary-700 space-y-2 ml-4">
                  <li>Virtual assistant services for real estate wholesaling and investment</li>
                  <li>Cold-calling campaigns to potential property sellers</li>
                  <li>Lead qualification and initial property assessment</li>
                  <li>CRM management and data entry services</li>
                  <li>Appointment setting and follow-up communications</li>
                  <li>Integration with real estate platforms and tools</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">3. Client Responsibilities</h2>
                <p className="text-secondary-700 mb-4">
                  As a Client, you agree to:
                </p>
                <ul className="list-disc list-inside text-secondary-700 space-y-2 ml-4">
                  <li>Provide accurate and complete information necessary for service delivery</li>
                  <li>Ensure all provided contact lists and data comply with applicable laws and regulations</li>
                  <li>Maintain current real estate licenses and certifications as required by law</li>
                  <li>Comply with all Do Not Call (DNC) regulations and telemarketing laws</li>
                  <li>Provide clear instructions and guidelines for cold-calling campaigns</li>
                  <li>Respond promptly to leads and appointments generated by our Services</li>
                  <li>Pay all fees according to the agreed payment schedule</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">4. Service Standards and Performance</h2>
                <p className="text-secondary-700 mb-4">
                  One Call Away commits to:
                </p>
                <ul className="list-disc list-inside text-secondary-700 space-y-2 ml-4">
                  <li>Provide virtual assistants trained specifically in real estate wholesaling</li>
                  <li>Maintain professional communication standards in all client interactions</li>
                  <li>Deliver services during agreed business hours and time zones</li>
                  <li>Provide regular reporting on campaign performance and results</li>
                  <li>Maintain confidentiality of all client information and business data</li>
                  <li>Implement quality control measures and ongoing VA training</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">5. Payment Terms</h2>
                <p className="text-secondary-700 mb-4">
                  Payment terms are as follows:
                </p>
                <ul className="list-disc list-inside text-secondary-700 space-y-2 ml-4">
                  <li>Fees are based on the selected service package (Standard or Premium)</li>
                  <li>Monthly fees are due in advance on the agreed billing date</li>
                  <li>Setup fees, if applicable, are due upon service commencement</li>
                  <li>Late payments may incur additional fees and service suspension</li>
                  <li>All fees are non-refundable except as specifically stated in these Terms</li>
                  <li>Price changes require 30 days advance written notice</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">6. Service Level Agreement</h2>
                <p className="text-secondary-700 mb-4">
                  Our Service Level Agreement includes:
                </p>
                <ul className="list-disc list-inside text-secondary-700 space-y-2 ml-4">
                  <li><strong>Availability:</strong> Services available during agreed business hours (typically US time zones)</li>
                  <li><strong>Response Time:</strong> Initial response to client communications within 24 hours</li>
                  <li><strong>Quality Standards:</strong> All VAs complete our proprietary real estate training program</li>
                  <li><strong>Reporting:</strong> Weekly performance reports provided to all clients</li>
                  <li><strong>Support:</strong> Dedicated account management for Premium package clients</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">7. Compliance and Legal Requirements</h2>
                <p className="text-secondary-700 mb-4">
                  Both parties must comply with applicable laws, including:
                </p>
                <ul className="list-disc list-inside text-secondary-700 space-y-2 ml-4">
                  <li>Telephone Consumer Protection Act (TCPA) and Do Not Call regulations</li>
                  <li>Fair Credit Reporting Act (FCRA) requirements</li>
                  <li>State and federal real estate licensing requirements</li>
                  <li>Data protection and privacy laws</li>
                  <li>Anti-spam and telemarketing regulations</li>
                </ul>
                <p className="text-secondary-700 mt-4">
                  Clients are solely responsible for ensuring their use of our Services complies with all applicable laws in their jurisdiction.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">8. Termination</h2>
                <p className="text-secondary-700 mb-4">
                  Either party may terminate this agreement:
                </p>
                <ul className="list-disc list-inside text-secondary-700 space-y-2 ml-4">
                  <li><strong>For Convenience:</strong> With 30 days written notice</li>
                  <li><strong>For Cause:</strong> Immediately upon material breach of these Terms</li>
                  <li><strong>Non-Payment:</strong> After 15 days of unpaid fees</li>
                </ul>
                <p className="text-secondary-700 mt-4">
                  Upon termination, we will securely return or delete client data as requested, and clients remain responsible for all fees incurred up to the termination date.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">9. Limitation of Liability</h2>
                <p className="text-secondary-700">
                  One Call Away's liability is limited to the fees paid for the specific services that gave rise to the claim. We are not liable for indirect, incidental, special, or consequential damages, including lost profits or business opportunities. Our Services are provided "as is" without warranties of any kind.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">10. Confidentiality</h2>
                <p className="text-secondary-700">
                  Both parties agree to maintain the confidentiality of proprietary information, business strategies, client data, and trade secrets. This obligation survives termination of this agreement. We implement industry-standard security measures to protect all client information.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">11. Intellectual Property</h2>
                <p className="text-secondary-700">
                  One Call Away retains all rights to our proprietary methodologies, training materials, and service delivery processes. Clients retain ownership of their business data and contact lists. Any improvements or customizations developed specifically for a client may be used by One Call Away for other clients unless otherwise agreed in writing.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">12. Dispute Resolution</h2>
                <p className="text-secondary-700">
                  Any disputes arising from these Terms shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association. The arbitration shall be conducted in English and governed by the laws of the State of Florida.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">13. Modifications</h2>
                <p className="text-secondary-700">
                  We reserve the right to modify these Terms at any time. Material changes will be communicated via email with 30 days notice. Continued use of our Services after such changes constitutes acceptance of the modified Terms.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-secondary-900 mb-4">14. Contact Information</h2>
                <p className="text-secondary-700 mb-4">
                  For questions about these Terms or our Services, please contact us:
                </p>
                <div className="bg-primary-50 p-6 rounded-xl">
                  <p className="text-secondary-800 mb-2"><strong>One Call Away</strong></p>
                  <p className="text-secondary-700 mb-2">Email: <a href="mailto:Info@OneCallAway.com" className="text-primary-600 hover:text-primary-700">Info@OneCallAway.com</a></p>
                  <p className="text-secondary-700">Phone: +1 (555) 123-4567</p>
                </div>
              </section>

            </div>

            {/* Back to Home Link */}
            <div className="mt-12 pt-8 border-t border-secondary-200">
              <Link 
                href="/"
                className="inline-flex items-center text-primary-600 hover:text-primary-700 font-semibold transition-colors"
              >
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                </svg>
                Back to Home
              </Link>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  )
}
